### ISSUE TITLE
ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by MrCsabaToth** [menloparklab/cohere-weaviate-wikipedia-retrieval#3]
What could be the reason for this error?
```
csaba$ gunicorn app:app
[2023-11-13 00:05:57 -0800] [32186] [INFO] Starting gunicorn 20.1.0
[2023-11-13 00:05:57 -0800] [32186] [INFO] Listening at: http://127.0.0.1:8000 (32186)
[2023-11-13 00:05:57 -0800] [32186] [INFO] Using worker: sync
[2023-11-13 00:05:57 -0800] [32195] [INFO] Booting worker with pid: 32195
[2023-11-13 00:05:57 -0800] [32195] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/csaba/anaconda3/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/csaba/anaconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/csaba/anaconda3/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/csaba/anaconda3/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/csaba/anaconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/home/csaba/anaconda3/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/csaba/anaconda3/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/home/csaba/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'app'
[2023-11-13 00:05:57 -0800] [32195] [INFO] Worker exiting (pid: 32195)
[2023-11-13 00:05:57 -0800] [32186] [INFO] Shutting down: Master
[2023-11-13 00:05:57 -0800] [32186] [INFO] Reason: Worker failed to boot.
```

**Comment by MrCsabaToth** [comment]
PEBKAC (was in the wrong directory)
